export default {
  hot_choco: require("../../assets/images/001-hot-chocolate.png"),
  tangerine: require("../../assets/images/002-tangerine.png"),
  candy_canes: require("../../assets/images/003-candy-canes.png"),
  gingerbread_man: require("../../assets/images/004-food-and-restaurant.png"),
  mince_pie: require("../../assets/images/005-food-and-restaurant-2.png"),
  ham:require('../../assets/images/006-food-and-restaurant-3.png'),
  cracker:require('../../assets/images/007-food-and-restaurant-4.png'),
  cookie:require('../../assets/images/008-food-and-restaurant-5.png'),
  chicken:require('../../assets/images/009-food-and-restaurant-6.png'),
  holly_cake:require('../../assets/images/010-food-and-restaurant-7.png'),
  jelly:require('../../assets/images/011-food-and-restaurant-8.png'),
  shrimp:require('../../assets/images/012-food-and-restaurant-9.png'),
  cane_cake:require('../../assets/images/013-food-and-restaurant-10.png'),
  shmores:require('../../assets/images/014-food-and-restaurant-11.png'),
  holly_cupcake:require('../../assets/images/015-food-and-restaurant-12.png'),
  leek:require('../../assets/images/016-food-and-restaurant-1.png'),
  meatball:require('../../assets/images/017-meatball.png'),
  brownies:require('../../assets/images/018-brownies.png'),
  milk:require('../../assets/images/019-food-and-restaurant-13.png'),
	pomegranate:require('../../assets/images/020-food-and-restaurant-14.png'),
	rice_pudding:require('../../assets/images/021-rice-pudding.png'),
	pig:require('../../assets/images/022-food-and-restaurant-15.png'),
	cod:require('../../assets/images/023-cod.png'),
	christmas_ball:require('../../assets/images/024-christmas-ball.png'),
	hat:require('../../assets/images/025-hat.png'),
	candle:require('../../assets/images/026-candle.png'),
	holly:require('../../assets/images/027-christmas.png'),
	muffin:require('../../assets/images/028-muffin.png'),
	cookie_milk:require('../../assets/images/029-milk.png'),
	lights:require('../../assets/images/031-christmas-1.png'),
  // tangerine:require('../../assets/images/002-tangerine.png'),
  // tangerine:require('../../assets/images/002-tangerine.png'),
  // tangerine:require('../../assets/images/002-tangerine.png'),
  // tangerine:require('../../assets/images/002-tangerine.png'),
};
